name: Deploy Development to AWS EC2

on:
  push:
    branches:
      - dev
    paths:
      - "lib/**"
      - "test/**"
      - "web/**"
      - pubspec.yaml
      - pubspec.lock
      - analysis_options.yaml

permissions:
  contents: read

concurrency:
  group: frontend-aws-ec2-development
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run Remote Command via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/healthsync/mkaix.healthsyncfe/
            git checkout dev
            git pull --ff-only origin dev
            flutter build web
            sudo systemctl reload nginx
